### ISSUE TITLE
Unhandled exception in M4 with pubspec.lock on unittest and meta set to 0.5.11+1

### ISSUE THREAD

**Issue by thetechnaddict** [butlermatt/dart_koans#6]
I was receiving an error Exception: No constructor 'Future.immediate' declared in class 'Future'. and saw that unittest and meta were locked to 0.4.5 and also found this thread - 

[](https://groups.google.com/a/dartlang.org/forum/?fromgroups#!topic/misc/CsNCwKpwACA)

So I changed the pubspec.lock to allow the libraries to be updated - now I have a different error....

Unhandled exception:
RangeError: 3 
#0      List.[](dart:core-patch/growable_array.dart:125:3)
#1      ConfigKoans.onSummary (package:dart_koans/src/config_koans.dart:101:49)
#2      _completeTests (package:unittest/unittest.dart:800:20)
#3      _nextBatch (package:unittest/unittest.dart:771:21)
#4      runTests.runTests.<anonymous closure> (package:unittest/unittest.dart:718:15)
#5      _asyncRunCallback._asyncRunCallback (dart:async/event_loop.dart:15:17)
#6      _asyncRunCallback._asyncRunCallback (dart:async/event_loop.dart:25:9)
#7      Timer.Timer.<anonymous closure> (dart:async-patch/timer_patch.dart:9:15)
#8      _Timer._createTimerHandler._handleTimeout (timer_impl.dart:99:28)
#9      _Timer._createTimerHandler._handleTimeout (timer_impl.dart:107:7)
#10     _Timer._createTimerHandler.<anonymous closure> (timer_impl.dart:115:23)
#11     _ReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:81:92)

**Comment by butlermatt** [comment]
Thanks for filing. To be honest, much of the code has not been updated recently to reflect various library changes that have occurred. On first inspection, it appears to be a bug with custom unittest library that the Koans makes use of. I'll try and take a look this afternoon or tomorrow.

Thanks again.

**Comment by butlermatt** [comment]
This has been corrected. An updated version of unittest is now available in the pubspec.lock file and changes made to the stackTrace mechanism so it properly parses file name and location. Tests should work as expected now. This is current with dart SDK: 0.5.16_r23799 and unittest 0.5.16 (now in the constraints)
